import { ConflictException, ForbiddenException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { EntityManager, DataSource } from 'typeorm';
import { AuditService } from '../../common/audit/audit.service';
import { IdempotencyService } from '../../common/idempotency/idempotency.service';

@Injectable()
export class OperationDaysService {
  constructor(private readonly dataSource: DataSource, private readonly idempotency: IdempotencyService, private readonly audit: AuditService) {}
  private async vendorId(manager: EntityManager, userId: string) { const [vendor] = await manager.query(`SELECT id FROM vendors WHERE user_id=$1`, [userId]); if (!vendor) throw new ForbiddenException('Profil vendor tidak ditemukan'); return vendor.id as string; }
  async create(userId: string, menuPlanId: string, key?: string) { return this.idempotency.execute(userId, key, { menuPlanId }, async (manager, correlationId) => { const vendorId = await this.vendorId(manager, userId); const [menu] = await manager.query(`SELECT * FROM menu_plans WHERE id=$1 AND vendor_id=$2 FOR UPDATE`, [menuPlanId, vendorId]); if (!menu) throw new NotFoundException('Menu plan tidak ditemukan'); const shortages = await manager.query(`SELECT mi.product_id, mi.unit, (mi.quantity_per_pax * $2) - COALESCE(SUM(l.quantity_delta), 0) shortage FROM menu_plan_items mi LEFT JOIN inventory_ledger l ON l.vendor_id=$1 AND l.product_id=mi.product_id AND l.unit=mi.unit WHERE mi.menu_plan_id=$3 GROUP BY mi.product_id, mi.unit, mi.quantity_per_pax HAVING (mi.quantity_per_pax * $2) > COALESCE(SUM(l.quantity_delta), 0)`, [vendorId, menu.target_pax, menu.id]); if (shortages.length) throw new UnprocessableEntityException({ code: 'INSUFFICIENT_INVENTORY', shortages }); const [day] = await manager.query(`INSERT INTO operation_days (vendor_id, menu_plan_id, operation_date) VALUES ($1,$2,$3) RETURNING *`, [vendorId, menu.id, menu.operation_date]); const eventId = await this.audit.record(manager,{actorUserId:userId,aggregateType:'operation_day',aggregateId:day.id,action:'operation.created',after:{status:day.status,operationDate:day.operation_date},correlationId}); return { body:{id:day.id,status:day.status,allowedNext:['CP1']},eventId}; }); }
  async today(userId: string) { return this.dataSource.transaction(async manager => { const vendorId=await this.vendorId(manager,userId); const [day]=await manager.query(`SELECT * FROM operation_days WHERE vendor_id=$1 AND operation_date=CURRENT_DATE`,[vendorId]); if(!day) return null; const next=day.status==='planned'?'CP1':day.status==='in_progress'?'CP2':day.status==='dispatched'?'CP4':day.status==='school_confirmed'?'close':null; return {id:day.id,status:day.status,allowedNext:next?[next]:[]}; }); }
  async consumeForCp1(manager: EntityManager, operationDayId: string, actorUserId: string) { const [day]=await manager.query(`SELECT od.*, mp.target_pax FROM operation_days od JOIN menu_plans mp ON mp.id=od.menu_plan_id WHERE od.id=$1 FOR UPDATE`,[operationDayId]); if(!day) throw new NotFoundException('Operation day tidak ditemukan'); if(day.status!=='planned') throw new ConflictException('CP1 tidak diizinkan untuk status operation day ini'); const items=await manager.query(`SELECT product_id,unit,quantity_per_pax FROM menu_plan_items WHERE menu_plan_id=$1`,[day.menu_plan_id]); for(const item of items){ const [balance]=await manager.query(`SELECT COALESCE(SUM(quantity_delta),0) quantity FROM inventory_ledger WHERE vendor_id=$1 AND product_id=$2 AND unit=$3`,[day.vendor_id,item.product_id,item.unit]); const required=Number(item.quantity_per_pax)*Number(day.target_pax); if(Number(balance.quantity)<required) throw new UnprocessableEntityException('Stok tidak cukup untuk CP1'); await manager.query(`INSERT INTO inventory_ledger (vendor_id,product_id,unit,quantity_delta,entry_type,source_type,source_id,actor_user_id) VALUES ($1,$2,$3,$4,'consumption','operation_day',$5,$6)`,[day.vendor_id,item.product_id,item.unit,-required,operationDayId,actorUserId]); } await manager.query(`UPDATE operation_days SET status='in_progress',updated_at=NOW() WHERE id=$1`,[operationDayId]); return day; }
  async activeForVendor(manager: EntityManager, vendorId: string) { const [day]=await manager.query(`SELECT * FROM operation_days WHERE vendor_id=$1 AND operation_date=CURRENT_DATE FOR UPDATE`,[vendorId]); if(!day) throw new ConflictException('Operation day hari ini belum dibuat'); return day; }
}
